services:
  api:
    build: ./backend
    container_name: blog-backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - ADMIN_SECRET=${ADMIN_SECRET}
      - TZ=America/Sao_Paulo
    volumes:
      - /home/otavio/letracaixad_prod/database.db:/app/data/database.db
    networks:
      - blog-network
      - cloudflare_net

  web:
    build:
      context: ./frontend
      args:
        PUBLIC_API_URL: ${PUBLIC_API_URL}
    container_name: blog-frontend
    restart: always
    environment:
      - PUBLIC_API_URL=${PUBLIC_API_URL}
      - INTERNAL_API_URL=http://api:8000
      - TZ=America/Sao_Paulo
    depends_on:
      - api
    networks:
      - blog-network
      - cloudflare_net

networks:
  cloudflare_net:
    external: true
  blog-network:
