name: Production Deploy

on:
  push:
    branches:
      - master

# Remove o erro de depreciação do Node 20
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    runs-on: self-hosted
    if: github.event_name == 'push'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Para não apagar a base de dados do meu servidor
          clean: false

      - name: Deploy with Docker Compose
        run: |
          docker compose -f docker-compose.yaml up -d --build

      - name: Clean up old images
        run: docker image prune -f
